spring.application.name=backend

#SERVER

server.port=${SERVER_PORT:8085}
server.servlet.context-path=${GLOBAL_PATH:/airline}


# BD (Neon.tech)

spring.datasource.url=${DB_URL:jdbc:postgresql://ep-royal-smoke-ampjv0aq-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_1XgT4EydoCfW}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Pool (Hikari)

spring.datasource.hikari.pool-name=AirplaneTicketPool
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.keepalive-time=30000

# Date format
spring.jackson.date-format=dd/MM/yyyy HH:mm:ss
spring.jackson.time-zone=America/Bogota
spring.mvc.format.date-time=dd/MM/yyyy HH:mm:ss

# Custom Logger Config Hora, Hilo, Nivel, Clase, Mensaje
logging.pattern.console=%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n

logging.file.name=logs/airplane-booking.log
logging.pattern.file=%d{dd/MM/yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

#Logs
logging.level.org.springframework.web=DEBUG